day1/book_store/book/urls.py
from django.urls import path
from .views import book_index,book_details,book_delete,book_update,add_book,book_create


#& to make namespace
app_name="book"

urlpatterns = [
    path("",book_index,name="book-index"),
    path("<int:bid>/",book_details,name="book-details"),
    path('book_delete/<int:bid>', book_delete, name="book-delete"),
    path('book_update/<int:bid>/', book_update, name="book-update"),
    path('create/', book_create, name="book-create"),
    path('add/', add_book, name="create"),

]

day1/book_store/book_store/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
 
    path("books/",include("book.urls")),
]

day1/book_store/book/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=255,unique=True)
    description=models.TextField("book description")
    rate=models.PositiveSmallIntegerField(default=0)
    views=models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

day1/book_store/book/forms.py
from django.forms import ModelForm
from .models import Book


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'description', 'rate','views']

day1/book_store/book/views.py
from django.shortcuts import redirect, render
from .models import Book
from .forms import BookForm



# books_list=[
#    {
#         'index': 0,
#         'id': 1,
#         'name': 'book-1',
#         'author': "Yousef",
#         'description': "Learning Learnin gJSfffjk dfjdklg jkdgjdkgjdkgjd kgjdkgjdglk jdgkljfjfjejekgjekgjekgjekgjgekjgekLearningJSfffjkdfjdklgjkdgjdkgjdkgjdkgjdkgjdglkjdgkljfjfjejekgjekgjekgjekgjgekjgekLearningJSfffjkdfjdklgjkdgjdkgjdkgjdkgjdkgjdglkjdgkljfjfjejekgjekgjekgjekgjgekjgek",
#     },
#     {
#         'index': 1,
#         'id': 2,
#         'name': 'book-2',
#         'author': "Ahmed",
#         'description': "Learning LearningJS fffjkdfjd klgjkdgjdkgjdkgjdkgjd kgjdglkjdgk ljfj fjejekgjekgjekgjekgjgekjgek",
#     },
#     {
#         'index': 2,
#         'id': 3,
#         'name': 'book-3',
#         'author': "Ali",
#         'description': "LearningJS fffjk dfjdklgjkdg jdkgjdkgjd kgjdkgjdglkjdgkl jfjfjejekg jekgjekgjekgjgekjgek",
#     },
# ]




# def get_book(book_id):
#     for book in books_list:
#         if book["id"] == book_id:
#             return book
#     return None



      
    
   

# Create your views here.
def book_index(request):
   books=Book.objects.all()
   return render(request,"all_books.html",context={"books":books})

def book_details(request,bid):
   book=Book.objects.get(pk=bid)
   return render(request,"book_details.html",context={"book":book})



def book_delete(request, bid):
    book=Book.objects.get(pk=bid).delete()
    return redirect('book:book-index')   

def book_update(request, bid):
    book = Book.objects.get(pk=bid)
    form = BookForm(instance=book)
    if request.method == "POST":
        form = BookForm(data=request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect("book:book-details", bid=book.id)
    return render(request, 'update_book.html', context={
        'form': form, 
        'book': book
    })

def book_create(request):
    form = BookForm()
    return render(request, 'create_book.html', context={
        'form': form
    })





def add_book(request):
    
        #& why if I decalre size outside it can not see it?
        # size=len(books_list)+1
        # print(request.POST)
        # new_book={
        #     "id":size,
        #     "name":request.POST['name'],
        #     "author":request.POST['author'],
        #     "description":request.POST['description']
        #     }
        # books_list.append(new_book)
        # size+=1
    form = BookForm()
    if request.method == "POST":
        form = BookForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("book:book-index")

day1/book_store/book/templates/all_books.html
{% extends "base_templates.html" %}


{% block title %}
    books list
{% endblock %}


{% block main-content%}
<a class="btn btn-success" href="{% url 'book:book-create' %}"> Create</a>
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">BOOK title</th>
        <th scope="col">Rate</th>
        <th scope="col">Description</th>
        <th scope="col">ACTIONS</th>
      </tr>
    </thead>
    <tbody>
        {%for book in books%}
      <tr>
        <th scope="row">{{book.id}}</th>
        <td>{{book.title}}</td>
        <td>{{book.rate}}</td>
        <td>{{book.description| truncatewords:3|title}}</td>
        <td>
            <a class="btn btn-info" href="{% url 'book:book-details' book.id %}"> View</a>
            <a class="btn btn-success" href="{% url 'book:book-update' book.id %}"> Update</a>
            <a class="btn btn-danger" href="{% url 'book:book-delete' book.id %}"> Delete</a>
        </td>
      </tr>

      {# if list is empty#}
      {% empty %}
      <tr>
       <td colspan="3" class="text-center"> sorry, not task in list</td>
      </tr>

      {%endfor%}
    </tbody>
  </table>
{%endblock%}

day1/book_store/book/templates/book_details.html
{% extends "base_templates.html" %}


{%block title%}
book details
{%endblock%}


{%block main-content%}
<h2>book details</h2>
<ul>
    <li>id: {{book.id}}</li>
    <li>title: {{book.title}}</li>
    <li>description: {{book.description}}</li>
    <li>rating: {{book.rate}}</li>

</ul>
{%endblock%}

day1/book_store/book/templates/create_book.html
{% extends "base_templates.html" %}


{%block title%}
create book
{%endblock%}


{%block main-content%}
<h2>create book</h2>
<form method="post" action="{% url 'book:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    {% comment%}
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">name</label>
      <input type="text" class="form-control" name="name" id="exampleInputEmail1" aria-describedby="emailHelp">
     
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">author</label>
      <input type="text" class="form-control" name="author" id="exampleInputPassword1">
    </div>

    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">description</label>
        <input type="text" class="form-control" name="description" id="exampleInputPassword1">
      </div>

      

    <button type="submit" class="btn btn-primary">Submit</button>

    {% endcomment %}

    <button type="submit" class="btn btn-primary">Submit</button>
    <div class="text-center mt-5" style="display:inline">
        <a href="{% url 'book:book-index'%}">
            <button type="button" class="btn btn-info">
                Back to book Index
            </button>
        </a>
    </div>

  </form>
{%endblock%}

day1/book_store/book/templates/update_book.html
{% extends "base_templates.html" %}
{% block main-content %}
<div class="container">
    <div class="row">
        <div class="text-center col-12">

            <form method="post" action="{% url 'book:book-update' book.id %}">
                {% csrf_token %}
                {{form.as_p}}


                <button type="submit" class="btn btn-primary">Submit</button>
                <div class="text-center mt-5" style="display:inline">
                    <a href="{% url 'book:book-index'  %}">
                        <button type="button" class="btn btn-info">
                            Back to list
                        </button>
                    </a>
                </div>
            </form>
        </div>


    </div>
</div>
{% endblock %}